import type { Subcategory, Category } from './elite-category-system';

export const FINAL_ELITE_SYSTEM: Record<string, Category> = {
  development: {
    id: 'development',
    name: '技术开发',
    name_en: 'Development',
    description: '硬核技术能力，专业开发者必备。全栈面试、代码评审、架构设计一站式解决方案',
    icon: '💻',
    color: 'indigo',
    gradient: 'from-indigo-500 to-purple-600',
    priority: 1,
    featured: true,
    appCount: 9,
    subcategories: [
      {
        id: 'frontend',
        name: '前端开发',
        name_en: 'Frontend',
        icon: '🎨',
        description: 'React/Vue/TypeScript 工业级最佳实践',
        eliteSkills: ['React专家', 'Vue架构师', 'TypeScript大师'],
      },
      {
        id: 'backend',
        name: '后端架构',
        name_en: 'Backend',
        icon: '🏗️',
        description: 'API设计/数据库/微服务/高并发',
        eliteSkills: ['API架构师', '数据库专家'],
      },
      {
        id: 'devops',
        name: '工程效能',
        name_en: 'DevOps',
        icon: '🚀',
        description: '容器化/CI-CD/云原生架构',
        eliteSkills: ['Docker专家', '全栈面试官', '代码评审官'],
      },
      {
        id: 'codequality',
        name: '代码质量',
        name_en: 'Code Quality',
        icon: '✨',
        description: '重构/测试/技术债务治理',
        eliteSkills: ['代码重构专家'],
      },
    ],
  },
  content: {
    id: 'content',
    name: '内容创作',
    name_en: 'Content Creation',
    description: '从0到1打造爆款内容。短视频脚本、小红书文案、直播话术、私域运营全套模板',
    icon: '✍️',
    color: 'purple',
    gradient: 'from-purple-500 to-pink-600',
    priority: 2,
    featured: true,
    appCount: 12,
    subcategories: [
      {
        id: 'professional',
        name: '专业写作',
        name_en: 'Professional',
        icon: '📝',
        description: '体制内公文、商务邮件标准输出',
        eliteSkills: ['公文写作专家', '商务邮件大师', '学术论文助手'],
      },
      {
        id: 'marketing',
        name: '营销爆款',
        name_en: 'Marketing',
        icon: '📣',
        description: '10万+方法论，涨粉变现一条龙',
        eliteSkills: ['短视频脚本', '公众号小编', '广告文案大师', '小红书爆款', '直播话术', '文案鬼才', '私域运营专家'],
      },
      {
        id: 'creative',
        name: '创意写作',
        name_en: 'Creative',
        icon: '🌈',
        description: '小说、剧本、脑洞创意',
        eliteSkills: ['小说创作家'],
      },
    ],
  },
  business: {
    id: 'business',
    name: '商业管理',
    name_en: 'Business',
    description: '创业者、管理者必备。商业计划、股权设计、品牌定位、运营增长核心方法论',
    icon: '📊',
    color: 'blue',
    gradient: 'from-blue-500 to-cyan-600',
    priority: 3,
    featured: true,
    appCount: 10,
    subcategories: [
      {
        id: 'strategy',
        name: '战略决策',
        name_en: 'Strategy',
        icon: '🎯',
        description: '商业分析、竞争策略、顶层设计',
        eliteSkills: ['SWOT分析专家', '竞品分析师', '商业计划书', '股权设计专家', '品牌定位专家', '商业模式设计师'],
      },
      {
        id: 'operation',
        name: '运营增长',
        name_en: 'Operations',
        icon: '📈',
        description: '用户增长、数据驱动、转化提升',
        eliteSkills: ['用户运营专家', '数据分析师'],
      },
      {
        id: 'finance',
        name: '财务管理',
        name_en: 'Finance',
        icon: '💰',
        description: '财报分析、预算管控、投融资',
        eliteSkills: ['财务报表专家'],
      },
    ],
  },
  education: {
    id: 'education',
    name: '教育学习',
    name_en: 'Education',
    description: '高效学习、职业晋升。雅思托福、论文降重、公考面试、读书学习',
    icon: '🎓',
    color: 'emerald',
    gradient: 'from-emerald-500 to-teal-600',
    priority: 4,
    featured: true,
    appCount: 14,
    subcategories: [
      {
        id: 'language',
        name: '语言考试',
        name_en: 'Language',
        icon: '🌍',
        description: '雅思/托福 满分方法论',
        eliteSkills: ['雅思写作', '托福口语', '翻译官'],
      },
      {
        id: 'thinking',
        name: '思维学习',
        name_en: 'Thinking',
        icon: '🧠',
        description: '结构化思考、高效学习法',
        eliteSkills: ['结构化思考', '费曼学习法', '论文降重助手', '公考申论大师', '思维导图大师', '时间管理专家', '读书拆书家'],
      },
      {
        id: 'career',
        name: '职业技能',
        name_en: 'Career',
        icon: '💼',
        description: '面试、汇报、职场硬技能',
        eliteSkills: ['面试辅导', 'PPT大师', 'Excel专家'],
      },
    ],
  },
  lifestyle: {
    id: 'lifestyle',
    name: '生活服务',
    name_en: 'Lifestyle Services',
    description: '高情商生活指南。婆媳关系、酒桌文化、情感咨询、健身饮食、育儿法律',
    icon: '🌟',
    color: 'rose',
    gradient: 'from-rose-500 to-orange-500',
    priority: 5,
    featured: false,
    appCount: 14,
    subcategories: [
      {
        id: 'emotion',
        name: '情商社交',
        name_en: 'Social',
        icon: '💝',
        description: '情感、人际、高情商沟通',
        eliteSkills: ['心理咨询师', '恋爱顾问', '婆媳关系专家', '酒桌文化大师', '职场情商大师'],
      },
      {
        id: 'health',
        name: '健康生活',
        name_en: 'Health',
        icon: '💪',
        description: '健身、饮食、养生、育儿、宠物',
        eliteSkills: ['健身私教', '营养师', '育儿专家', '宠物医生助手', '中医养生师'],
      },
      {
        id: 'utility',
        name: '实用工具',
        name_en: 'Utilities',
        icon: '🛠️',
        description: '起名、简历、法律、出行',
        eliteSkills: ['起名大师', '简历优化', '律师助手'],
      },
    ],
  },
  entertainment: {
    id: 'entertainment',
    name: '创意娱乐',
    name_en: 'Entertainment',
    description: '沉浸式角色对话、文字游戏模拟器。和历史名人对话、重开人生',
    icon: '🎮',
    color: 'amber',
    gradient: 'from-amber-500 to-yellow-500',
    priority: 6,
    featured: false,
    appCount: 5,
    subcategories: [
      {
        id: 'roleplay',
        name: '经典角色',
        name_en: 'Role Play',
        icon: '🎭',
        description: '和智者对话、向名人学习',
        eliteSkills: ['诸葛亮', '曹操', '福尔摩斯'],
      },
      {
        id: 'game',
        name: '文字游戏',
        name_en: 'Text Games',
        icon: '🎲',
        description: '沉浸式互动模拟',
        eliteSkills: ['人生重开模拟器', '修仙模拟器'],
      },
    ],
  },
};

export function getFinalEliteList(): string[] {
  const all: string[] = [];
  for (const cat of Object.values(FINAL_ELITE_SYSTEM)) {
    for (const sub of cat.subcategories) {
      all.push(...sub.eliteSkills);
    }
  }
  return all;
}
